package com.hrullo.examen.simulator;

public class Constantes {
	
   public final static String RESUEMEN_FILMS = "{\r\n"
   		+ "   \"resumen\":[\r\n"
   		+ "      {\r\n"
   		+ "         \"cantidad\":5,\r\n"
   		+ "         \"titulos\":[\r\n"
   		+ "            \"A New Hope\",\r\n"
   		+ "            \"The Empire Strikes Back\",\r\n"
   		+ "            \"Return of the Jedi\",\r\n"
   		+ "            \"Revenge of the Sith\",\r\n"
   		+ "            \"The Force Awakens\"\r\n"
   		+ "         ],\r\n"
   		+ "         \"persona\":\"Luke Skywalker\"\r\n"
   		+ "      },\r\n"
   		+ "      {\r\n"
   		+ "         \"cantidad\":6,\r\n"
   		+ "         \"titulos\":[\r\n"
   		+ "            \"A New Hope\",\r\n"
   		+ "            \"The Empire Strikes Back\",\r\n"
   		+ "            \"Return of the Jedi\",\r\n"
   		+ "            \"The Phantom Menace\",\r\n"
   		+ "            \"Attack of the Clones\",\r\n"
   		+ "            \"Revenge of the Sith\"\r\n"
   		+ "         ],\r\n"
   		+ "         \"persona\":\"C-3PO\"\r\n"
   		+ "      },\r\n"
   		+ "      {\r\n"
   		+ "         \"cantidad\":7,\r\n"
   		+ "         \"titulos\":[\r\n"
   		+ "            \"A New Hope\",\r\n"
   		+ "            \"The Empire Strikes Back\",\r\n"
   		+ "            \"Return of the Jedi\",\r\n"
   		+ "            \"The Phantom Menace\",\r\n"
   		+ "            \"Attack of the Clones\",\r\n"
   		+ "            \"Revenge of the Sith\",\r\n"
   		+ "            \"The Force Awakens\"\r\n"
   		+ "         ],\r\n"
   		+ "         \"persona\":\"R2-D2\"\r\n"
   		+ "      },\r\n"
   		+ "      {\r\n"
   		+ "         \"cantidad\":4,\r\n"
   		+ "         \"titulos\":[\r\n"
   		+ "            \"A New Hope\",\r\n"
   		+ "            \"The Empire Strikes Back\",\r\n"
   		+ "            \"Return of the Jedi\",\r\n"
   		+ "            \"Revenge of the Sith\"\r\n"
   		+ "         ],\r\n"
   		+ "         \"persona\":\"Darth Vader\"\r\n"
   		+ "      },\r\n"
   		+ "      {\r\n"
   		+ "         \"cantidad\":5,\r\n"
   		+ "         \"titulos\":[\r\n"
   		+ "            \"A New Hope\",\r\n"
   		+ "            \"The Empire Strikes Back\",\r\n"
   		+ "            \"Return of the Jedi\",\r\n"
   		+ "            \"Revenge of the Sith\",\r\n"
   		+ "            \"The Force Awakens\"\r\n"
   		+ "         ],\r\n"
   		+ "         \"persona\":\"Leia Organa\"\r\n"
   		+ "      },\r\n"
   		+ "      {\r\n"
   		+ "         \"cantidad\":3,\r\n"
   		+ "         \"titulos\":[\r\n"
   		+ "            \"A New Hope\",\r\n"
   		+ "            \"Attack of the Clones\",\r\n"
   		+ "            \"Revenge of the Sith\"\r\n"
   		+ "         ],\r\n"
   		+ "         \"persona\":\"Owen Lars\"\r\n"
   		+ "      },\r\n"
   		+ "      {\r\n"
   		+ "         \"cantidad\":3,\r\n"
   		+ "         \"titulos\":[\r\n"
   		+ "            \"A New Hope\",\r\n"
   		+ "            \"Attack of the Clones\",\r\n"
   		+ "            \"Revenge of the Sith\"\r\n"
   		+ "         ],\r\n"
   		+ "         \"persona\":\"Beru Whitesun lars\"\r\n"
   		+ "      },\r\n"
   		+ "      {\r\n"
   		+ "         \"cantidad\":1,\r\n"
   		+ "         \"titulos\":[\r\n"
   		+ "            \"A New Hope\"\r\n"
   		+ "         ],\r\n"
   		+ "         \"persona\":\"R5-D4\"\r\n"
   		+ "      },\r\n"
   		+ "      {\r\n"
   		+ "         \"cantidad\":1,\r\n"
   		+ "         \"titulos\":[\r\n"
   		+ "            \"A New Hope\"\r\n"
   		+ "         ],\r\n"
   		+ "         \"persona\":\"Biggs Darklighter\"\r\n"
   		+ "      },\r\n"
   		+ "      {\r\n"
   		+ "         \"cantidad\":6,\r\n"
   		+ "         \"titulos\":[\r\n"
   		+ "            \"A New Hope\",\r\n"
   		+ "            \"The Empire Strikes Back\",\r\n"
   		+ "            \"Return of the Jedi\",\r\n"
   		+ "            \"The Phantom Menace\",\r\n"
   		+ "            \"Attack of the Clones\",\r\n"
   		+ "            \"Revenge of the Sith\"\r\n"
   		+ "         ],\r\n"
   		+ "         \"persona\":\"Obi-Wan Kenobi\"\r\n"
   		+ "      }\r\n"
   		+ "   ]\r\n"
   		+ "}";
	
	public final static String RESPUESTA_CSV = "{\r\n"
			+ "    \"REGIONES\": [\r\n"
			+ "        {\r\n"
			+ "            \"region\": \"Australia and Oceania\",\r\n"
			+ "            \"cantidad\": 79\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"region\": \"Asia\",\r\n"
			+ "            \"cantidad\": 136\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"region\": \"Europe\",\r\n"
			+ "            \"cantidad\": 267\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"region\": \"Central America and the Caribbean\",\r\n"
			+ "            \"cantidad\": 99\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"region\": \"Middle East and North Africa\",\r\n"
			+ "            \"cantidad\": 138\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"region\": \"North America\",\r\n"
			+ "            \"cantidad\": 19\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"region\": \"Sub-Saharan Africa\",\r\n"
			+ "            \"cantidad\": 262\r\n"
			+ "        }\r\n"
			+ "    ],\r\n"
			+ "    \"ITEMS TYPES\": [\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 87,\r\n"
			+ "            \"itemType\": \"Baby Food\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 97,\r\n"
			+ "            \"itemType\": \"Vegetables\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 87,\r\n"
			+ "            \"itemType\": \"Personal Care\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 89,\r\n"
			+ "            \"itemType\": \"Office Supplies\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 77,\r\n"
			+ "            \"itemType\": \"Household\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 78,\r\n"
			+ "            \"itemType\": \"Clothes\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 82,\r\n"
			+ "            \"itemType\": \"Snacks\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 75,\r\n"
			+ "            \"itemType\": \"Cosmetics\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 79,\r\n"
			+ "            \"itemType\": \"Cereal\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 101,\r\n"
			+ "            \"itemType\": \"Beverages\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 78,\r\n"
			+ "            \"itemType\": \"Meat\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 70,\r\n"
			+ "            \"itemType\": \"Fruits\"\r\n"
			+ "        }\r\n"
			+ "    ],\r\n"
			+ "    \"ORDERS PRIORITY\": [\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 262,\r\n"
			+ "            \"orderPriority\": \"C\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 228,\r\n"
			+ "            \"orderPriority\": \"H\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 268,\r\n"
			+ "            \"orderPriority\": \"L\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 242,\r\n"
			+ "            \"orderPriority\": \"M\"\r\n"
			+ "        }\r\n"
			+ "    ],\r\n"
			+ "    \"SALES CHANNELS\": [\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 520,\r\n"
			+ "            \"salesChannels\": \"Offline\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 480,\r\n"
			+ "            \"salesChannels\": \"Online\"\r\n"
			+ "        }\r\n"
			+ "    ],\r\n"
			+ "    \"COUNTRY\": [\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 8,\r\n"
			+ "            \"country\": \"Benin\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"Papua New Guinea\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 8,\r\n"
			+ "            \"country\": \"Angola\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"Cambodia\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 8,\r\n"
			+ "            \"country\": \"Sudan\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 8,\r\n"
			+ "            \"country\": \"East Timor\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 2,\r\n"
			+ "            \"country\": \"Kazakhstan\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"Portugal\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"Syria\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Grenada\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 7,\r\n"
			+ "            \"country\": \"Solomon Islands\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"North Korea\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"Greece\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 2,\r\n"
			+ "            \"country\": \"Latvia\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 9,\r\n"
			+ "            \"country\": \"Mongolia\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 8,\r\n"
			+ "            \"country\": \"Iran\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Morocco\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 8,\r\n"
			+ "            \"country\": \"Mali\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 7,\r\n"
			+ "            \"country\": \"Marshall Islands\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"Panama\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"Guatemala\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 3,\r\n"
			+ "            \"country\": \"Iraq\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"Laos\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"Nepal\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 8,\r\n"
			+ "            \"country\": \"Tunisia \"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 2,\r\n"
			+ "            \"country\": \"The Gambia\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"Tanzania\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Ukraine\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 2,\r\n"
			+ "            \"country\": \"Zambia\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"Belize\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 8,\r\n"
			+ "            \"country\": \"Ghana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 10,\r\n"
			+ "            \"country\": \"Bahrain\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"India\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 3,\r\n"
			+ "            \"country\": \"Canada\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 7,\r\n"
			+ "            \"country\": \"Maldives\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 7,\r\n"
			+ "            \"country\": \"Guinea-Bissau\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 8,\r\n"
			+ "            \"country\": \"Turkey\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 7,\r\n"
			+ "            \"country\": \"Belgium\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"The Bahamas\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"Namibia\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Comoros\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Taiwan\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"Finland\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Trinidad and Tobago\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"South Africa\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 7,\r\n"
			+ "            \"country\": \"Central African Republic\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"Georgia\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"Democratic Republic of the Congo\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 3,\r\n"
			+ "            \"country\": \"Jamaica\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 2,\r\n"
			+ "            \"country\": \"Turkmenistan\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"Germany\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"Yemen\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"Mauritius \"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 3,\r\n"
			+ "            \"country\": \"Eritrea\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 3,\r\n"
			+ "            \"country\": \"Samoa \"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 9,\r\n"
			+ "            \"country\": \"Fiji\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"Guinea\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 7,\r\n"
			+ "            \"country\": \"Chad\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 7,\r\n"
			+ "            \"country\": \"Somalia\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"Sao Tome and Principe\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Madagascar\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"Thailand\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"Libya\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Equatorial Guinea\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"Kiribati\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 7,\r\n"
			+ "            \"country\": \"Moldova \"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Costa Rica\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 7,\r\n"
			+ "            \"country\": \"Sweden\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 7,\r\n"
			+ "            \"country\": \"Vietnam\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 7,\r\n"
			+ "            \"country\": \"Malawi\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 7,\r\n"
			+ "            \"country\": \"Andorra\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 3,\r\n"
			+ "            \"country\": \"Liechtenstein\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 9,\r\n"
			+ "            \"country\": \"Poland\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"Kuwait\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"Nigeria\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 7,\r\n"
			+ "            \"country\": \"Bulgaria\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 8,\r\n"
			+ "            \"country\": \"Jordan\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 3,\r\n"
			+ "            \"country\": \"Croatia\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"Sri Lanka\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"United Kingdom\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"Tuvalu\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"United Arab Emirates\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Kenya\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 8,\r\n"
			+ "            \"country\": \"Switzerland\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"Spain\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 3,\r\n"
			+ "            \"country\": \"Brunei\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Lebanon\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Djibouti\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 3,\r\n"
			+ "            \"country\": \"Azerbaijan\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 11,\r\n"
			+ "            \"country\": \"Cuba\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 8,\r\n"
			+ "            \"country\": \"Liberia\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 10,\r\n"
			+ "            \"country\": \"Czech Republic\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 3,\r\n"
			+ "            \"country\": \"Mauritania\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"Burkina Faso\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"Saint Lucia\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 8,\r\n"
			+ "            \"country\": \"Swaziland\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Palau\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 2,\r\n"
			+ "            \"country\": \"San Marino\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 7,\r\n"
			+ "            \"country\": \"Israel\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 3,\r\n"
			+ "            \"country\": \"Australia\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 7,\r\n"
			+ "            \"country\": \"Tajikistan\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 8,\r\n"
			+ "            \"country\": \"Estonia\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"Myanmar\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 1,\r\n"
			+ "            \"country\": \"Cameroon\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"Cyprus\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 10,\r\n"
			+ "            \"country\": \"Malaysia\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Iceland\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"Oman\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Armenia\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"Gabon\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"South Korea\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"Austria\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"Mozambique\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"El Salvador\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Monaco\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 7,\r\n"
			+ "            \"country\": \"Luxembourg\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"Saint Kitts and Nevis \"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Algeria\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"Slovenia\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 7,\r\n"
			+ "            \"country\": \"Lesotho\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Tonga\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Republic of the Congo\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Hungary\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 8,\r\n"
			+ "            \"country\": \"South Sudan\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 8,\r\n"
			+ "            \"country\": \"Japan\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 9,\r\n"
			+ "            \"country\": \"Belarus\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 8,\r\n"
			+ "            \"country\": \"Albania\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"New Zealand\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 9,\r\n"
			+ "            \"country\": \"Vanuatu\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Senegal\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"Honduras\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"Italy\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"Macedonia\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 2,\r\n"
			+ "            \"country\": \"Nauru\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Ethiopia\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Haiti\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"Afghanistan\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"Burundi\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 3,\r\n"
			+ "            \"country\": \"Singapore\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"Antigua and Barbuda \"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"United States of America\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 7,\r\n"
			+ "            \"country\": \"Egypt\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 2,\r\n"
			+ "            \"country\": \"Federated States of Micronesia\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 3,\r\n"
			+ "            \"country\": \"Sierra Leone\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Seychelles \"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"Vatican City\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 1,\r\n"
			+ "            \"country\": \"Malta\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 7,\r\n"
			+ "            \"country\": \"Russia\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"Saudi Arabia\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"Cape Verde\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Netherlands\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 8,\r\n"
			+ "            \"country\": \"Pakistan\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 1,\r\n"
			+ "            \"country\": \"Kosovo\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"China\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 7,\r\n"
			+ "            \"country\": \"Ireland\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 8,\r\n"
			+ "            \"country\": \"Qatar\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Slovakia\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Serbia\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 3,\r\n"
			+ "            \"country\": \"France\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Lithuania\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"Bosnia and Herzegovina\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Kyrgyzstan\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 6,\r\n"
			+ "            \"country\": \"Bhutan\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 8,\r\n"
			+ "            \"country\": \"Romania\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 2,\r\n"
			+ "            \"country\": \"Togo\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 9,\r\n"
			+ "            \"country\": \"Niger\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"Philippines\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Rwanda\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Cote d'Ivoire\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Uzbekistan\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Bangladesh\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 3,\r\n"
			+ "            \"country\": \"Nicaragua\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 3,\r\n"
			+ "            \"country\": \"Barbados\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 7,\r\n"
			+ "            \"country\": \"Norway\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 4,\r\n"
			+ "            \"country\": \"Saint Vincent and the Grenadines\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 3,\r\n"
			+ "            \"country\": \"Botswana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 2,\r\n"
			+ "            \"country\": \"Denmark\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 7,\r\n"
			+ "            \"country\": \"Dominican Republic\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 5,\r\n"
			+ "            \"country\": \"Uganda\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 2,\r\n"
			+ "            \"country\": \"Mexico\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 10,\r\n"
			+ "            \"country\": \"Zimbabwe\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 7,\r\n"
			+ "            \"country\": \"Montenegro\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 8,\r\n"
			+ "            \"country\": \"Greenland\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 2,\r\n"
			+ "            \"country\": \"Dominica\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"cantidad\": 3,\r\n"
			+ "            \"country\": \"Indonesia\"\r\n"
			+ "        }\r\n"
			+ "    ]\r\n"
			+ "}";

}
