
-- Base  de datos para el CSV

drop TABLE if EXISTS beancsv;


CREATE TABLE beancsv (
REGION VARCHAR(100),
COUNTRY VARCHAR(100),
ITEMTYPE VARCHAR(100),
SALESCHANNELS VARCHAR(100),
ORDERPRIORITY VARCHAR (100),
ORDERDATE VARCHAR(100),
ORDERID INTEGER,
SHIPDATE VARCHAR(100),
UNITSSOLD FLOAT,
UNITPRICE FLOAT,
UNITCOST FLOAT,
TOTALREVENUE FLOAT,
TOTALCOAST FLOAT,
TOTALPROFIT FLOAT,
PRIMARY KEY  (ORDERID)
);



 
 